# Generated by Django 4.2.2 on 2023-06-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentdetails",
            name="appointment_date",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
