# Generated by Django 4.2.2 on 2023-06-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_alter_appointmentdetails_appointment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentdetails",
            name="appointment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
