# Generated by Django 4.2.2 on 2023-06-28 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_alter_appointmentdetails_appointment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentdetails",
            name="name",
        ),
    ]
