# Generated by Django 4.2.2 on 2023-06-29 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_alter_patient_contact_details"),
        ("appointment", "0005_rename_patient_appointmentdetails_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentdetails",
            name="patient_id",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.patient",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentdetails",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
