# Generated by Django 4.2.2 on 2023-06-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "contact_details",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("dob", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("transgender", "Transgender"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("address", models.CharField(max_length=255, null=True)),
                ("medical_history", models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.patient",
                    ),
                ),
            ],
        ),
    ]
