# Generated by Django 4.2.2 on 2023-06-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_patient_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="contact_details",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
